### ISSUE TITLE
Hi, problems on log in

### ISSUE THREAD

**Issue by Gracrys** [petrovicstefanrs/ratefolio#1] opened 2019-02-20 18:24 UTC
When i try to log in to the page from github or google sends me an error saying: A network error (such as timeout, interrupted connection or unreachable host) has occurred, logged from firefox and just fine

**Comment by petrovicstefanrs** [comment] 2019-02-20 19:55
Hi, I'm not sure I understand exactly what the issue is. Also I see you managed to publish a post on the platform. Does that mean the issue you had is resolved? If not some further explanation and some screenshoots would be great!

**Comment by Gracrys** [comment] 2019-02-20 20:36
Yeah sorry, forgot to say the error occurred when logging in brave browser, when i logged in firefox worked just fine

**Comment by petrovicstefanrs** [comment] 2019-02-20 23:58
Could be the Brave browser issue. Maybe its blocking firebase. Since the issue didn't persist I'm closing this thread

**Closed as completed by petrovicstefanrs** 2019-02-20 23:58 UTC
